import type { LooseUnion } from "@sv443-network/coreutils";
import { getDefaultStaticData } from "@util/data.ts";
import { buildNumber, buildTimestamp, mode, scriptInfo } from "@/constants.ts";
import { millis } from "@util/index.ts";
import type { FeatureKey, PerformanceReport } from "@/types.ts";
import packageJson from "@root/package.json" with { type: "json" };

export const perfReport: PerformanceReport = {
  _comments: [
    `This is a performance report generated by ${scriptInfo.name} (${packageJson.homepage})`,
    "It shows the amount of time (in ms) it took to complete various stages of the initialization process.",
    "- The 'start' property is a 13-digit epoch timestamp representing the time at which the script started running.",
    "- The timings in the 'durations' property are generic measurements of how long certain phases are. These measurements do not start at the 'start' property timestamp.",
    "- The timings in the 'featureDurations' property are measurements of how long it took for each individual feature entrypoint to initialize, starting from the beginning of the feature initialization phase - also refer to 'featuresAllReady_deferred' in the 'durations' property.",
    "- 'resources' will only contain entries whenever the resource cache was empty on startup (like on a fresh install, or if the resource cache is cleared through the userscript manager extension's storage management tool). Its 'fetchAttempts' prop will be an object mapping a resource key to the amount of times it was fetched.",
    "- The entries in the 'observers' property are timestamps of two types; whenever an observer 'checked' for elements, and whenever an observer 'found' elements (tuple of timestamp and amount of elements found).",
  ],
  meta: {
    version: scriptInfo.version,
    buildNumber,
    buildTime: new Date(buildTimestamp).toISOString(),
    mode,
    domain: "ytm", // initialized in index.ts:preInit() because of circular dependency shit
    userAgent: navigator.userAgent,
    scriptHandler: GM.info?.scriptHandler ?? "unknown",
    scriptHandlerVersion: GM.info?.version ?? "unknown",
    // @ts-expect-error - Violentmonkey-only property
    injectInto: GM.info?.injectInto ?? null,
    isIncognito: GM.info?.isIncognito ?? null,
    isFirstPartyIsolation: GM.info?.isFirstPartyIsolation ?? null,
    sandboxMode: GM.info?.sandboxMode ?? null,
  },
  durations: {} as PerformanceReport["durations"],
  featureStart: 0,
  featureDurations: {} as PerformanceReport["featureDurations"],
  start: 0,
  sinceStart: {},
  resources: {},
  observers: {},
};

export const _ = () => getDefaultStaticData();

/**
 * Starts a timer for measuring the duration of a specific phase of the initialization process.  
 * Returns a function that, when called, will stop the timer and save the duration in the `initTimings` object under the specified name.
 */
export function measureInitDuration(name: LooseUnion<keyof PerformanceReport & FeatureKey>): () => void {
  const start = Date.now();
  return () => {
    if(typeof perfReport.durations !== "object")
      perfReport.durations = {} as PerformanceReport["durations"];
    perfReport.durations![name] = Date.now() - start;
  };
}

/** Records when a {@linkcode globservers} instance checks for elements and finds elements, to record the event times to the {@linkcode perfReport}. */
export function recordObserverTick<TObsName extends keyof PerformanceReport["observers"], TType extends "checked" | "found">(globserverName: TObsName, type: TType, ...results: TType extends "checked" ? [] : [numElements: number]) {
  if(typeof perfReport.observers[globserverName] !== "object")
    perfReport.observers[globserverName] = {} as PerformanceReport["observers"][TObsName];

  const obsData = [...perfReport.observers[globserverName]![type] ?? []];

  if(type === "checked")
    (obsData as number[]).push(millis());
  else
    (obsData as [number, number][]).push([millis(), (results as [number])[0]]);

  // @ts-expect-error idw deal with this
  perfReport.observers[globserverName]![type] = obsData;
}
