name: Build BetterYTM

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [22.x]

    env:
      CI: "true"
      STORE_PATH: ""
      PNPM_VERSION: 10
      RETENTION_DAYS_PUSH: 30
      RETENTION_DAYS_PR: 2

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v5
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Get version info
        id: get_version_info
        run: |
          BYTM_VERSION=$(node src/tools/get-pkg-prop.mjs version)
          echo "BYTM_VERSION=$BYTM_VERSION" >> $GITHUB_OUTPUT
          GIT_SHA_SHORT=$(git rev-parse --short HEAD)
          echo "GIT_SHA_SHORT=$GIT_SHA_SHORT" >> $GITHUB_OUTPUT

      - name: Build all for production
        run: pnpm run build-prod

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: "BetterYTM v${{ steps.get_version_info.outputs.BYTM_VERSION }} (${{ steps.get_version_info.outputs.GIT_SHA_SHORT }}) [${{ github.run_number }}]"
          path: dist
          retention-days: ${{ github.event_name == 'push' && env.RETENTION_DAYS_PUSH || env.RETENTION_DAYS_PR }}
