name: "Build BetterYTM"

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    timeout-minutes: 8

    strategy:
      matrix:
        node-version: [21.x]

    env:
      CI: "true"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies # runs the npm ci command to install from package-lock.json
        run: npm ci
      - name: Build all for production
        run: npm run build-prod
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
