name: "Lint BetterYTM"

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    timeout-minutes: 8

    strategy:
      matrix:
        node-version: [22.x]

    env:
      CI: "true"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies # runs the npm ci command to install from package-lock.json
        run: npm ci
      - name: Build with tsc & lint
        run: npm run lint
