name: "Lint BetterYTM"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main, develop] # runs on every push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x]

    env:
      CI: "true"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies # runs the npm ci command to install from package-lock.json
        run: npm ci
      - name: Build with tsc & lint
        run: npm run lint
